### ISSUE TITLE
Exception trace if falek8-copyright is enabled

### ISSUE THREAD

**Issue by dobesv** [savoirfairelinux/flake8-copyright#3]
It seems like the plugin is reporting the error on line `0` which causes this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flake8/main.py", line 36, in main
    report = flake8_style.check_files()
  File "/usr/local/lib/python2.7/dist-packages/flake8/engine.py", line 181, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "/usr/local/lib/python2.7/dist-packages/flake8/engine.py", line 172, in _retry_serial
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pep8.py", line 1842, in check_files
    runner(path)
  File "/usr/local/lib/python2.7/dist-packages/flake8/engine.py", line 126, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/usr/local/lib/python2.7/dist-packages/pep8.py", line 1619, in check_all
    return self.report.get_file_results()
  File "/usr/local/lib/python2.7/dist-packages/flake8/reporter.py", line 144, in get_file_results
    line = self.lines[line_number - 1]
IndexError: list index out of range
```

**Comment by ghost** [comment]
Hum, this issue should be closed, the PR was merged.
